LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 64
NUM_EPOCHS : 100
LINEAR_PROBING: True
PROBING_EPOCHS : 25

IMAGE_SIZE : 224

MODEL: ConvNeXtBase
PRETRAINED: True
FREEZE: True
LOSS: CrossEntropyLoss

DATASET: 0 # 0: CUB, 1: CUB and FGVC-Aircraft, 2: FoodX


LABEL_SMOOTHING: 0.1