LEARNING_RATE : 3e-4
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 64
NUM_EPOCHS : 50
FINETUNE: True
FINETUNE_EPOCHS : 30
FINETUNE_LR : 1e-5

WARMUP_EPOCHS : 10
WARMUP_LR : 1e-5

IMAGE_SIZE : 224

MODEL: ConvNeXtBase
PRETRAINED: True
FREEZE: True
LOSS: CrossEntropyLoss

DATASET: 2 # 0: CUB, 1: CUB and FGVC-Aircraft, 2: FoodX
CUT_UP_MIX: True
HPC: False

LABEL_SMOOTHING: 0.1