LEARNING_RATE : 1e-2
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 48
NUM_EPOCHS : 50
FINETUNE: True
FINETUNE_EPOCHS : 50
FINETUNE_LR : 1e-5

IMAGE_SIZE : 224

MODEL: ConvNeXtLarge
PRETRAINED: True
FREEZE: True
LOSS: CrossEntropyLoss

DATASET: 1 # 0: CUB, 1: CUB and FGVC-Aircraft, 2: FoodX
CUT_UP_MIX: True


LABEL_SMOOTHING: 0.1