LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 256
NUM_EPOCHS : 20
LINEAR_PROBING: False
PROBING_EPOCHS : 50

IMAGE_SIZE : 224

MODEL: ResNet50
PRETRAINED: True
LOSS: CrossEntropyLoss

DATASET: 0 # 0: CUB, 1: CUB and FGVC-Aircraft, 2: FoodX